export interface Bookingseized {
    "id": any,
    "user_id": any,
    "bus_operator_id": any,
    "name": any,
    "via": any,
    "bus_number": any,
    "bus_description": any,
    "bus_type_id": any,
    "bus_sitting_id": any,
    "bus_seat_layout_id": any,
    "cancellationslabs_id": any,
    "running_cycle": any,
    "popularity": any,
    "admin_notes": any,
    "has_return_bus": any,
    "return_bus_id": any,
    "cancelation_points": any,
    "created_at": any,
    "updated_at": any,
    "created_by": "Admin",
    "status": any,
    "sequence": any,
    "bookingseized": any,
    "bus_operator":any,
    "ticket_price":any,
  
}
