export interface Busoperator {
    id:any;
    email_id:string;
    password:string;
    operator_name:string;
    contact_number:string;
    organisation_name:string;
    location_name:string;
    address:string;
    operator_info:any;
    additional_email:any;
    additional_contact:any;
    bank_account_name:string;
    bank_name:string;
    bank_ifsc:string;
    bank_account_number:string;
    need_gst_bill:any;
    gst_number:string;
    gst_amount:any;
}
